learn_django2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from app1 import views
from app1.views import depart, user, number, admin, account, order, chart, upload

urlpatterns = [
    # path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    # 部门管理
    path('depart/list', depart.depart_list),
    path('depart/add', depart.depart_add),
    path('depart/del', depart.depart_del),
    path('depart/<int:nid>/edit', depart.depart_edit),
    path('depart/multi', depart.depart_multi),

    # 用户管理
    path('user/list', user.user_list),
    path('user/add', user.user_add),
    path('user/<int:nid>/edit', user.user_edit),
    path('user/<int:nid>/del', user.user_del),

    # 靓号管理
    path('number/list', number.number_list),
    path('number/add', number.number_add),
    path('number/<int:nid>/edit', number.number_edit),
    path('number/<int:nid>/del', number.number_del),

    # 管理员管理
    path('admin/list', admin.admin_list),
    path('admin/add', admin.admin_add),
    path('admin/<int:nid>/edit', admin.admin_edit),
    path('admin/<int:nid>/del', admin.admin_del),
    path('admin/<int:nid>/reset', admin.admin_reset),

    path('login', account.login),
    path('logout', account.logout),

    path('order/list', order.order_list),
    path('order/add', order.order_add),
    path('order/delete', order.order_del),
    path('order/detail', order.order_detail),
    path('order/edit', order.order_edit),

    path('chart/list', chart.chart_list),
    path('chart/line', chart.chart_line),
    path('chart/bar', chart.chart_bar),
    path('chart/pie', chart.chart_pie),

    path('upload/list', upload.upload_list),
    path('upload/form', upload.upload_form),
    path('upload/model/form', upload.upload_model_form)
]

app1/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    """ 管理员表 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)

    def __str__(self):
        return self.username

class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name='入职时间')
    create_time = models.DateField(verbose_name='入职时间')

    # 级联删除
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)
    # 置空
    # depart_id = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', null=True, blank=True, on_delete=models.SET_NULL)
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)


class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices, default=1)
    price = models.IntegerField(verbose_name='价格', default=0)
    status_choices = (
        (1, '已占用'),
        (2, '未占用'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=2)


class Order(models.Model):
    """ 订单 """
    oid = models.CharField(verbose_name='订单号', max_length=64)
    title = models.CharField(verbose_name='名称', max_length=64)
    price = models.IntegerField(verbose_name='价格')
    status_choices = (
        (1, '待支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name='管理员', to='Admin', to_field='id', on_delete=models.CASCADE)

class Boss(models.Model):
    """ 老板表 """
    name = models.CharField(verbose_name='姓名', max_length=16)
    age = models.IntegerField(verbose_name='年龄')
    img = models.CharField(verbose_name='头像', max_length=128)

class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name='城市名', max_length=32)
    count = models.IntegerField(verbose_name='人口数量')
    img = models.FileField(verbose_name='Logo', max_length=128, upload_to='city/')

app1/views/account.py
from django.shortcuts import render, redirect

from django import forms

from app1 import models
from app1.utils.bootstrap import BootstrapForm
from app1.utils.encrypt import md5


class LoginForm(BootstrapForm):
    username = forms.CharField(label='用户名', max_length=32, widget=forms.TextInput)
    password = forms.CharField(label='密码', max_length=32, widget=forms.PasswordInput)

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)
def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm(data=request.POST)
        if form.is_valid():
            admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
            if not admin_obj:
                form.add_error('password', '用户名或密码错误')
                return render(request, 'login.html', {'form': form})
            request.session['info'] = {'id': admin_obj.id, 'name': admin_obj.username}
            return redirect('/admin/list')


        print(form.errors)
        return render(request, 'login.html', {'form': form})

def logout(request):
    request.session.clear()
    return redirect('/login')

app1/views/admin.py
from django.shortcuts import render, redirect
from app1 import models
from app1.utils.pagination import Pagination
from app1.utils.encrypt import md5



def admin_list(request):
    # for i in range(10):
    #     models.Admin.objects.create(username='123', password='123456')
    info = request.session.get('info')
    if not info:
        return redirect('login')

    data_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['username__contains'] = search_data

    queryset = models.Admin.objects.all().filter(**data_dict)

    page_object = Pagination(request, queryset)
    context = {
        'admin_list': page_object.page_queryset,  # 分完页的数据
        'page_string': page_object.html(),  # 生成页码
    }

    return render(request, 'admin_list.html', context)


from django import forms
from app1.utils.bootstrap import BootstrapModelForm
class AdminModelForm(BootstrapModelForm):

    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput)
    class Meta:
        model = models.Admin
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        return md5(password)

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = md5(self.cleaned_data.get('confirm_password'))
        if password != confirm_password:
            raise forms.ValidationError('密码不一致')
        else:
            return confirm_password

class AdminEditModelForm(BootstrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']

class AdminResetModelForm(BootstrapModelForm):
    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput)
    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        md5_password = md5(password)

        if models.Admin.objects.filter(id=self.instance.pk, password=md5_password).exists():
            raise forms.ValidationError('密码与之前的相同')

        return md5_password

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = md5(self.cleaned_data.get('confirm_password'))
        if password != confirm_password:
            raise forms.ValidationError('密码不一致')
        else:
            return confirm_password
def admin_add(request):

    title = '新建管理员'

    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change.html', {'form': form, "title": title})
    else:
        form = AdminModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/admin/list')
        else:
            print(form.errors)
            return render(request, 'change.html', {'form': form, "title": title})


def admin_edit(request, nid):

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'admin_list.html')

    title = '编辑管理员'
    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {'form': form, "title": title})
    else:
        form = AdminEditModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect('/admin/list')
        else:
            print(form.errors)
            return render(request, 'change.html', {'form': form, "title": title})

def admin_del(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list')

def admin_reset(request, nid):

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'admin_list.html')

    title = '重置密码 - {}'.format(row_object.username)

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, 'change.html', {"form": form, "title": title})
    else:
        form = AdminResetModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect('/admin/list')
        else:
            print(form.errors)
            return render(request, 'change.html', {"form": form, "title": title})

app1/views/chart.py
from django.http import JsonResponse
from django.shortcuts import render


def chart_list(request):
    return render(request, 'chart_list.html')


def chart_bar(request):
    legend = ['手机', '电脑']
    series_list = [
        {
            'name': '手机',
            'type': 'bar',
            'data': [5, 20, 36, 10, 10, 20]
        },
        {
            'name': '电脑',
            'type': 'bar',
            'data': [15, 10, 16, 20, 30, 40]
        }
    ]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']

    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }

    return JsonResponse(result)


def chart_pie(request):
    db_data_list = [
        {"name": "直接访问", "value": 335},
        {"name": "邮件营销", "value": 310},
        {"name": "联盟广告", "value": 234},
        {"name": "视频广告", "value": 135},
        {"name": "搜索引擎", "value": 1548}
    ]

    result = {
        "status": True,
        "data": db_data_list,
    }

    return JsonResponse(result)


def chart_line(request):
    legend = ['邮件营销', '联盟广告', '视频广告',]
    series_list = [
        {
            'name': '邮件营销',
            'type': 'line',
            'stack': 'Total',
            'data': [120, 132, 101, 134, 90, 230, 210]
        },
        {
            'name': '联盟广告',
            'type': 'line',
            'stack': 'Total',
            'data': [220, 182, 191, 234, 290, 330, 310]
        },
        {
            'name': '视频广告',
            'type': 'line',
            'stack': 'Total',
            'data': [230, 382, 291, 334, 390, 330, 320]
        }
    ]
    x_axis = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']

    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series_list": series_list,
            "x_axis": x_axis,
        }
    }

    return JsonResponse(result)

app1/views/depart.py
import pandas as pd
from django.http import HttpResponse
from django.shortcuts import render, redirect
from app1 import models
from app1.utils.pagination import Pagination
from app1.utils.form import UserModelForm, NumberEditModelForm, NumberModelForm


# Create your views here.
def depart_list(request):

    queryset = models.Department.objects.all()

    page_obj = Pagination(request, queryset, page_size=10)
    context = {
        "depart_list": page_obj.page_queryset,
        'page_string': page_obj.html(),
    }

    return render(request, 'depart_list.html', context)
def depart_add(request):

    if request.method == 'GET':
        return render(request, 'depart_add.html')
    else:
        title = request.POST.get('title')
        models.Department.objects.create(title=title)
        return redirect('/depart/list')
def depart_del(request):
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()

    return redirect('/depart/list')
def depart_edit(request, nid):
    if request.method == 'GET':
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html', {'row_object': row_object})
    else:
        models.Department.objects.filter(id=nid).update(title=request.POST.get('title'))
        return redirect('/depart/list')

def depart_multi(request):

    file_obj = request.FILES.get("exc")

    # wb = load_workbook(file_obj)
    # sheet = wb.sheet[0]
    #
    # for row in sheet.iter_rows(min_row=2):
    #     text = row[0].value
    #
    #     models.Department.objects.create(title=text)
    df = pd.read_excel(file_obj)

    for index, row in df.iterrows():
        text = row[0]
        if not models.Department.objects.filter(title=text).exists():
            models.Department.objects.create(title=text)

    return redirect('/depart/list')

app1/views/order.py
import random

from django.shortcuts import render
from app1 import models
from app1.utils.bootstrap import BootstrapModelForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from datetime import datetime
from app1.utils.pagination import Pagination


class OrderModelForm(BootstrapModelForm):
    class Meta:
        model = models.Order
        # fields = "__all__"
        exclude = ['oid', 'admin']

def order_list(request):
    form = OrderModelForm()
    queryset = models.Order.objects.all().order_by('-id')
    page_obj = Pagination(request, queryset, page_size=10)
    context = {
        'form': form,
        "order_list": page_obj.page_queryset,
        'page_string': page_obj.html(),
    }

    return render(request, 'order_list.html', context)

@csrf_exempt
def order_add(request):
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        form.instance.oid = datetime.now().strftime('%Y%m%d%H%M%S') + str(random.randint(1000, 9999))
        form.instance.admin_id = request.session['info']['id']
        form.save()
        return JsonResponse({'status': True})

    return JsonResponse({'status': False, 'error': form.errors})

def order_del(request):
    nid = request.GET.get('nid')
    print(nid)
    if not models.Order.objects.filter(id=nid).exists():
        return JsonResponse({'status': False, 'error': '删除失败，数据不存在'})

    models.Order.objects.filter(id=nid).delete()
    return JsonResponse({'status': True})

def order_detail(request):
    nid = request.GET.get('nid')
    print(nid)
    order_dict = models.Order.objects.filter(id=nid).values('title', 'price', 'status').first()
    if not order_dict:
        return JsonResponse({'status': False, 'error': '数据不存在'})

    result = {
        'status': True,
        'data': order_dict
    }

    return JsonResponse(result)

@csrf_exempt
def order_edit(request):

    nid = request.GET.get('nid')
    print(nid)
    row_obj = models.Order.objects.filter(id=nid).first()
    if not row_obj:
        return JsonResponse({'status': False, 'tips': '数据不存在'})

    form = OrderModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})

    return JsonResponse({'status': False, 'error': form.errors})

app1/templates/admin_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div>
            <a class="btn btn-primary" href="/admin/add">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建管理员
            </a>
            <div style="float: right; width: 300px">
                <form method="get">
                    <div class="input-group">
                        <form action="get"></form>
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="subit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                    </div><!-- /input-group -->
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                管理员列表
            </div>


            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            {% for obj in admin_list %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.username }}</td>
                    <td>******</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit">编辑</a>
                        <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/reset">重置密码</a>
                        <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/del">删除</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
     <ul class="pagination">
            {{ page_string }}
            <li>
                <form style="float: left; margin-left: -1px" method="get">
                    <input name="page"
                        style="position: relative; float: left; display: inline-block; width: 80px; border-radius: 0;"
                           type="text"
                           class="form-control"
                           placeholder="页码"
                    >
                    <button type="submit" class="btn btn-primary" style="border-radius: 0;">跳转</button>
                </form>
            </li>
        </ul>
    </div>

{% endblock %}

app1/templates/order_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div>
            <input id="btnAdd" type="button" value="新建订单" class="btn btn-primary">
            <div style="float: right; width: 300px">
                <form method="get">
                    <div class="input-group">
                        <form action="get"></form>
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="subit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                    </div><!-- /input-group -->
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>


            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>名称</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>管理员</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in order_list %}
                    <tr uid="{{ obj.id }}">
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>
                            <input uid="{{ obj.id }}" class="btn btn-primary btn-xs btn-edit" type="button" value="编辑">
                            <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
            <li>
                <form style="float: left; margin-left: -1px" method="get">
                    <input name="page"
                           style="position: relative; float: left; display: inline-block; width: 80px; border-radius: 0;"
                           type="text"
                           class="form-control"
                           placeholder="页码"
                    >
                    <button type="submit" class="btn btn-primary" style="border-radius: 0;">跳转</button>
                </form>
            </li>
        </ul>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除？</h4>
                <p>删除后，所有关联的数据都会被删除</p>
                <p>
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDelEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $('#btnAdd').click(function () {
                EDIT_ID = undefined;
                $('#formAdd')[0].reset();
                $('#myModalLabel').text('新建订单')
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $('#btnSave').click(function () {

                $('.error-msg').empty();

                if (EDIT_ID) {
                    doEdit();
                } else {
                    doAdd();
                }


            })
        }

        function doEdit() {
            $.ajax({
                url: '/order/edit' + '?nid=' + EDIT_ID,
                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'json',
                success: function (res) {
                    if (res.status) {
                        {#alert('创建成功');#}
                        $('#formAdd')[0].reset();
                        $('#myModal').modal('hide');
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips);
                        } else {
                            $.each(res.error, function (name, errorList) {
                                $('#id_' + name).next().text(errorList[0]);
                            })
                        }
                    }
                }
            })
        }

        function doAdd() {
            $.ajax({
                url: '/order/add',
                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'json',
                success: function (res) {
                    if (res.status) {
                        {#alert('创建成功');#}
                        $('#formAdd')[0].reset();
                        $('#myModal').modal('hide');
                        location.reload();
                    } else {
                        $.each(res.error, function (name, errorList) {
                            $('#id_' + name).next().text(errorList[0]);
                        })
                    }
                }
            })
        }

        function bindBtnDelEvent() {
            $('.btn-delete').click(function () {
                $('#deleteModal').modal('show');

                DELETE_ID = $(this).attr('uid');
                console.log(DELETE_ID)

            })
        }

        function bindBtnConfirmDeleteEvent() {
            $('#btnConfirmDelete').click(function() {
                $.ajax({
                    url: '/order/delete',
                    type: 'get',
                    data: {
                        nid: DELETE_ID
                    },
                    dataType: 'json',
                    success: function (res) {
                        if (res.status) {
                            $('#deleteModal').modal('hide');
                            {#alert('删除成功')#}
                            location.reload();
                            {#$('tr[uid="' + DELETE_ID + '"]').remove();#}

                            DELETE_ID = 0;
                        } else {
                            alert(res.error);
                        }
                    }
                })
            })
        }

        function bindBtnEditEvent() {

            $('.btn-edit').click(function () {
                var current_id = $(this).attr('uid');
                EDIT_ID = current_id;
                $('#formAdd')[0].reset();
                $.ajax({
                    url: '/order/detail'
                    , type: 'get'
                    , data: {
                        nid: current_id
                    }
                    , dataType: 'json'
                    , success: function (res) {
                        if (res.status) {
                            $.each(res.data, function (name, value) {
                                $('#id_' + name).val(value);
                            })

                            $('#myModalLabel').text('编辑订单')
                            $('#myModal').modal('show');
                        } else {
                            alert(res.error);
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

app1/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div>
            <a class="btn btn-primary" href="/user/add">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>


            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            {% for obj in user_list %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.create_time|date:"Y-m-d"}}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/del">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
            <li>
                <form style="float: left; margin-left: -1px" method="get">
                    <input name="page"
                           style="position: relative; float: left; display: inline-block; width: 80px; border-radius: 0;"
                           type="text"
                           class="form-control"
                           placeholder="页码"
                    >
                    <button type="submit" class="btn btn-primary" style="border-radius: 0;">跳转</button>
                </form>
            </li>
        </ul>
    </div>
{% endblock %}